### ISSUE TITLE
CBM-II support broken

### ISSUE THREAD

**Issue by nils-eilers** [nils-eilers/NODISKEMU#15]
- DIRECTORY mostly fails
- fetching disk status with DOS wedge fails

**Comment by mnaberez** [comment]
> DIRECTORY mostly fails

I also noticed this on CBM-II intermittently when using the original PetSD with sd2iec-based firmware.

**Comment by nils-eilers** [comment]
This was "expected behavior" for the old IEEE-488 bus functions because they were a very ugly hack that was based on a timeout to make it (kind of) work: if the timeout was a bit too long, it broke, same if it was too short. The timing was "fine-tuned" for the old PETs.

The new bus functions doesn't contain any timings or delays. They're completely state-driven. There seems to be a timing-issue anyway...

**Comment by nils-eilers** [comment]
Maybe I've been too fast with this issue. It was filed due to experiences with a petSD+ built by somebody else and tested only with a single CBM-II machine.

Meanwhile I did try to reproduce those results on my own CBM-II machine with my own petSD+ but (unfortunately? luckily?) I simply can't: everything is working like a charm here!

HELP WANTED: Are there any CBM-II users out there? Could you please try the latest firmware version and report your results?

**Comment by nils-eilers** [comment]
I didn't receive further feedback, so I can only assume that if it works here, it will probably work somewhere else too: issue closed.

**Comment by mnaberez** [comment]
I have intended to test it but haven't gotten to it yet, sorry.  I only got NODISKEMU running a few days ago.  I pointed @sjgray at this issue and I think he intends to test it on the 610 also.  

A possible explanation for why it might work on your 610 but not another one might be the ROM versions.  When I was working on the [SoftBox](https://github.com/mnaberez/softbox) port for CBM-II, I found some differences in IEEE-488 behavior in the ROM versions and I [posted about it](http://www.vintage-computer.com/vcforum/showthread.php?27208-petSD&p=266380&highlight=#post266380) on VCF.  I solved my issue only doing a partial disassembly, so I can't say if there are other IEEE-488 differences between the ROM versions, but it might be worth investigating.

**Comment by nils-eilers** [comment]
The only user who reported problems was Christian Dirks just after he completed the assembly of his petSD+. Meanwhile he made it work somehow, he couldn't explain (or I didn't understand) what the problem was.

I'm aware of some differences between the ROM versions, so I made https://github.com/nils-eilers/CBM-II-KERNAL as an helper project to get a better understanding.

However, I won't make the efforts to test the bus functions with every available kernal version because of lack of time so NODISKEMU will clearly stay Bananaware here: delivered green and ripens with the customer.

However, IF there should appear an incompatibility with any kernal version somewhere, I'd really like to get informed and I'd be willing to try to fix it.

**Comment by mnaberez** [comment]
I've got 901244-04 on my 610 and @sjgray has 901244-03 on his.  Now that we have both have NODISKEMU, we can try it out and follow up.

**Comment by garacil** [comment]
Hi! I have a P500 with original (rewrited) firmware. Kernal 2 and Basic 2. PetSD+ do not work. The computer halt and device too.  Is normal? I need upgrade to any version? With a 710 I have the same results. Now I do not remember firmware version on that computer.
