### ISSUE TITLE
Make serial debug output a runtime option

### ISSUE THREAD

**Issue by nils-eilers** [nils-eilers/NODISKEMU#9]
Whether or not there are debug messages sent out to the serial line is currently a compile time option called CONFIG_UART_DEBUG. Sending a lot of debug messages may slow down the speed a device works with and sending too less may it happen that you don't get the required information that would be useful in a particular case. Making the output of debug messages a runtime option instead of a compile time option could allow sending more detailed messages if you need them and to completely disable them for the highest speed possible if everything is working well.

**Comment by ikorb** [comment]
Have you measured the slowdown?

**Comment by nils-eilers** [comment]
Not yet because the slowdown is obvious, but I'll do some measurements just for reference ASAP

**Comment by nils-eilers** [comment]
How embarrassing...
- ASAP = 16 days
- "obvious" feeling vs. measured facts:

Test case: CATALOG of a rather huge directory. BASIC 4's CATALOG has a huge bus protocol overhead because it fetches single bytes which produces a lot of debug output.

petSD (18.432 MHz, 115200 baud):
debug log disabled: 26.8 s
full debug log:  27.0 s

petSD+ (8 MHz, 38400 baud):
debug log disabled: 26.9 s
full debug log: 28.7 s

Anyway, many thanks for saving me from lots of work!
